In [24]:
input = """.@.@@@@@@@@@@@@.@.@..@@.@@@.@@.@@@@@@@.@.@@@@...@..@@.@@@.@@@@@@@@@...@@..@...@@...@..@.@.@.@.@.@@@@@.@..@@.@.@.@@@@.@@.@@@@..@@@@.@..@@
@@@@@.@@@.@@@.@@@@..@@@..@@@.@@@...@@@@@..@.@@@@@..@.@@.@@@.@.@.@@.@@.@@@@@.....@@..@@.@.@@.@@@@@@@@@@@@@@@.@@@@.@..@@@.@.@@@@@@.@@.@..@
@.@..@@@@@.@@@.@.@@.@@@@@@@..@@@@@@@..@@@@@@@.@@@@.@@.@@@.@.@@@.@@@.@@.@.@.@@.@@@.@.@@@.@..@@..@..@@..@@@@@@.@@...@@.....@@@@@@@..@@..@@
@.@@.@..@..@@@..@@@.@.@@.@.@@@@@.@@......@@@.@@@.@@@@@@.@.@.@@@@..@.@.@..@.@..@.@@.@...@@..@@@@@.@...@@@..@.@.@@@@@@@.@@@@@.@@@..@@@@.@.
.@.@..@.@@.@@@@.@@.@.@.@@@@@@.@@@@.....@@..@@.@.@@@@@@@@.@.@@@...@.@@...@@@@@@@@.@@...@@.@@@@@.@...@..@.@..@.@@@@@@@@@@@@@@@@@@@@.@@.@..
@@@@@.@@@@@.@@.@@@@@@@@.@@@.@..@@.@.@@@@@.@@@@.@..@.@@.@@@.@@.@@@@@.@.@@@.@@@..@@.@@@..@@@.@@@..@@..@@.@..@@@@.@.@@@.@.@@@@@.@@@@@@.@@..
@.@@@..@@@.@@@@@@@.@@@.@.@@@@@...@.@@@@@@@.@@.@.@@..@@@@.@.@.@.@@@@@@@@.@@@@@@@@.@.@@@.@@@@.@@@@.@@.@@@..@@@@.@@@@.@@@@@@..@@.@@.@@@@@.@
@@@.@@.@@@.@...@@@@...@.@@@..@@@@@@..@.@@@@@@.@..@@.@@@@@@@@@.@.....@@@@@@@@@@.@@..@@@.@@@.@.@@@@.@@..@@.@@.@@@@@..@@@@.@..@@.@.@...@@..
@@@@@.@.@..@@@@.@@@@@.@@.@.@..@@..@@@@@@.@@@@@@..@.@@@@@@..@@@.@@@@@@.@.@.@@@.@@..@@@@.@.@@@@.@@@@@@@.@@@@@@@@.@.@@@@...@@@.@@@@@@@...@@
.@.@@@..@@@.@@@.@@@@@..@.@.@..@..@@@....@@.@@.@@@.@.@@..@.@@@.@@@.@..@.@..@@@@@@@..@.@.@@@@@.@@@@.@.....@..@@@@@@@.@@.@@@@@.@..@@@@@@.@@
.@@..@@@.@@....@@@@.@@@@@.@@@@.@...@.@...@@@@@.@@@@@@.@@@@..@@.@@...@@@@@@@..@@@..@.@.@.@.@..@.@.@@..@@@@@@.@@@@@@.@.@@.@@@@.@.@@...@.@@
.@@.@@.@@@@@@.@@.@.@.@@@@.@@.@@.@@@@@@.@@@@@@@@@@.@@.@@.@@.@...@@@..@@@.@@.@@@@@.....@@@..@@.@@@@.@@.@.@@@@@@@@@@..@@..@.@.@.@@..@.@@@@@
@@@@@@@@@.@@@.@.@@@@@@@.@@@@@@@@@.@.@@@..@@@@.@..@@@....@...@..@@....@@@@@@@@.@@.@@..@@@@@@.@@@@.@@@@@@@@.@@@@...@.@.@@@@@.@@@..@@@@@@@@
@.@@@@@..@@.@@@@@.@..@@@@.@.@@@@..@.@..@@@@@@@@@@.@..@@.@..@.@.@..@.@@@@@@@@@.@@@.@@@@@@@@@@.@@@@@@..@@@...@@@@@@@.@@.@@@.@.@...@@....@@
@@@@@.@@..@@..@.@@@..@.@.@@@@@@..@@@@@@@@..@..@@@@@@@@@...@@@@@@@@@@@@..@@..@.@.@.@.@@.@@.@.@@..@@@@@@@.@@@@.@@@@@@@@..@@@@@.@.@@..@@@..
..@.@@@.@@@.@@.@@@@@@..@.@@@@@@.@.@@@@@@@@@@@@@.@...@.@...@@@@.@.@@@@@@@@..@@@@.@..@.@@.@@@.@@@@@@.@@@.@@@@@.@@@@.@@@@.@.@.@@..@@@@@.@@@
@@@.@@@@.@@@..@.@@.@@@@.@.@@@@@@.@@@..@@@@..@@.@.@@@@.@@@@.@.@@@..@@@@@@@@.@...@@@@@@@@@@@@@@@@@@@.@.@@.@@@.@.@@..@..@.@....@.@@.@..@..@
@.@@@@..@.@@.@@@@.@....@@@.@@.@.@@@.@.@@..@@.@@@.@@.@@@@@@@..@.@@@@@@@@@@..@@@@.@.@.@@@@.@@@@@.@@@...@@@@....@.@.@.@@@@@@@@@.@@@.@@.@@.@
.@@@..@@@....@@.@.@@@@@.@@.@@@@@@...@@.@@@@@@@@.@.@@@@@.@@.@.@@@@.@@.@@@@.@@.@@@@@...@.@@.@@@@@@@@.@.@.@@.@@..@.@.@@.@@.@.@@@@@.@.@.@@.@
@.@.@.@@@.@@@.....@.@@@@.@@@@.@@@@@...@.@@@.@@@@@@@@@.@@.@.@@@.@@@@.@@@@@@@..@.@@.@@@...@.@@@.@@@@.@@@@@@..@@@@@...@..@.@@@.@@.@@@@@@@@@
.@@.@.@@@.@@.@@@@@.@.@.@@.@@@@.@..@@@@..@@@@.@@@@.@@@@.@@..@@....@@@@@@..@@@.@@@@.@.@@..@.@@@@..@@@@@@@@@@.@@@.@@.@@@@..@@@.@@@.@@@@@..@
@@@@..@@@.@@.@@@@.@@@..@.@.@.@@@@@.@..@@@@.@@..@@@@.@@@@@@@@@@@@@.@..@@@@.@@@@@@@..@@.@@@@@@@.@@.@@@@@.@....@.@..@@@@@.@..@@...@.@@@.@@.
.@..@@.@@.@@@...@@@.....@@@...@@@@@@@....@.@@@.@@@..@@@@@@.@@@...@@@@@@..@@.@@@.@.@.@.@@@...@..@@@@.@@@.@..@@@@.@.@@@.@@@@@..@.@@@@..@@.
@@@@.@@@@..@@.@@..@@@.@.@@.@.@.@@@.@@.@@....@.@@...@@...@@@@@.@.@.@@@@.@@@@@@@.@.@.@@.@..@@@@.@..@..@@.@.@..@@@...@.@@@@@@@@@@@@@@@@.@@@
@@@@@..@.@@..@@@.@@.@@@@@.@.@@@@@.@..@@.@@@.@...@@@@@@@@.@@.@@..@@.@@@@@@@@.@..@@..@@..@.@@.@@...@.@.@@@@@@@@@@..@@@@@@@.@@@@.@@@@.@@@@.
@@@@@.@@@@@@.@@@@@..@@.@..@@@@@@.@.@@.@@@@@.@@@.@@.@@.@@..@...@@.@.@@@@@.@@@.@@@.@@.@@@@.@@@.@@@...@.@...@..@@@@@..@.@@@@.@@@...@@...@@.
@..@.@@.@..@@....@.@@@.@@@@@@@@.@@@..@.@@@@@@.@...@@.@@@..@......@.@@.@@....@.@@..@@@@@@@@@@@@@@..@@.@@.@@.@@@..@@@@@@@@..@.@@@@@.@@.@@@
.@@.@@@..@@@.@@@@@..@.@.@@.@@@@@@@@@.@@@.@@@@@..@@..@@@@.@..@...@@.@@..@...@@.@@@@@@.@..@@@.@.@@@@.@.@@.@.@@@@.@@@@@@@@.@.@@.@@@@@.@@...
@@@..@.@@....@@..@...@@.@..@@.@.@@..@@@@....@.@@@@.@@@@@@.@@@@.@@@.@@@@@@@@@@@.@..@@@@@@@@@@.@@@.@@@@@@@..@...@.@@@.@@.@.@@@....@@@.@@@@
.@@.@@@@@.@@.@@.@@..@@@@..@.@@...@..@@@@@.@.@@.@..@.@@@@@@.@@.@@...@.@@@@@@@@@.@.@.@...@.@.@@@...@.@@@@@@@@..@@...@.@@@@@@...@@.@@@@...@
@@@@@...@...@@@@..@@@@@.@@@@..@@@@@@@.@.@@@@@@.@@@@@@@@@@@@.@@@.@@@@.@@@.@.@@@@@.@..@@...@...@.@@..@@@.@.@@..@..@@@@@@...@@@@@@@@@@.@.@.
@.@@.@@@@@@@@@..@@@@@.@.@@@@.@....@@@@.@@@@..@..@@@.@@@@@@@..@@@@@@@..@.@...@@....@@@@@@@@@.@@@.@@@..@@@@@...@.@@@..@@.@@.@.@@@.@.@@.@@@
@@.@@@@@@@@@@@@@@@.@@@@@@..@..@.@@...@.@.@@@@@@@@@@@.@.@@@@@@.@.@@@@@@.@@@@.@@@...@@@@@@@.@@@..@@@@@@@@@@.@@@@@..@@.@@..@...@.@@@@@.@@@@
..@...@.@@@@@@..@@@.@@@@@@@@@.@@.@@@.@.@@.@@@.@.@@@.@.@@@@@@..@@.@.@@....@@@...@@@@@@@@@@@@@@@@@@@.@@@@@@.@@.@@@@@@@...@@@@@@@@@@.@..@@@
@@@.@@.@@.@.@@.@@.@@@@...@@@@@.@...@@.@.@.@.@@@.@.@.@@@@@@..@@..@...@.@@@.@.@@@@.@@@...@@@@@@.@@@@@@@@@.@@..@.@..@..@@.@.@@@@@@...@@..@@
@.@@.@@@@.@@@@@@@@@@.@@@.@@@.@@@@@@@@@@.@@@..@.@@......@.@@@@@@@@@@@@@....@@@@.@..@.@...@@@@@@.@..@@..@@@.@.@@@.@.@@.@..@..@@@.@..@@..@@
@@@@@@.@.@@@...@@.@@@@...@@@@@@..@@@@.@.@.@..@@@@.@..@@@@.@.@...@@@@@@@@@..@@@.@.@.@@@..@@@@@@@..@@@@@@@.@.@@@..@@.@@@..@@.@@@..@@.@@.@@
@@..@@@@.@.@.@@@@.@@.@@...@@@.@@@@.@@.@@@@@.@@@@.@.@.@@.@@@@@..@..@@@.@..@.@..@@.@.@@@@@@.@.@@@@@@@@.@@@@@@@@@.@@.@@.@..@....@@@@@@@@.@.
.@@.@.@@..@.@.@@@@@.@@@@@@.@@@.@@.@@@@.@.@@@@@@@@@@.@.@@@@@.@..@.@@.@.@....@.@.@@.@@.@..@@@@@@@@@@@@@...@@@@.@...@@@@.@@@@..@@..@.@.@@.@
@.@@@@@@@@@@@@@@.@.@@@.@.@.@@.@..@@@...@@.@@.@.@@.@@.@@@@@@@.@.@..@@...@@@@.@.@.@@.@...@@@@@..@@@@@@@@@..@@.@....@@@@@@@@.@@...@@@@@.@@.
..@@@.@@@@@@.@.@@@@@@@@@@@@@.@.@.@@@.@...@.@@@...@@.@@@..@@...@@..@.@@.@@@@@@@.@.@@@@@@.@.@@.@@.@@@@@@...@@@.@@@.@.@.@@.@..@.@@..@@@@@@@
...@.@.@.@.@@..@@.@@.@.@@.@..@@@.@.@..@@..@@@..@@@.@@.@...@@.@@.@@@@....@.@.@@.@@.@.@.@.@@.@@.@@@....@@@@@.@@@.@.@.@@@.@.@..@@..@@@@.@@@
@@@@@@@@@@@@@.@.@@@.@..@@@.@.@.@.@@..@..@@@@@@@@@..@.@..@.@@..@.@@@@.@@@@@@@@@@@@..@..@@@.@..@@..@..@@@@.@@@@@.@@..@.@@@@.....@@..@..@@@
@@.@..@@.@..@@.@@.@..@@...@@.@.@@...@.@..@@@@@@@@..@@@.@@@@@@@@.@@...@@..@@@@@@@@@.@@....@@...@.@@.@@.@.@@@@@.@@@@.@@@..@...@.@.@@.@@@@@
@@.@@@@@@..@.@@@@@.@@@@.@@..@@@@@@@.@@@.@.@.@@@@@@@@.@.@@@@..@..@.@.@@@...@@@@@.@@.@.@@..@.@.@.@@.@@.@@....@@..@@.@.@@@@@@....@.....@@..
@@@@@.@@.@.@@@.@@@..@@@@@@@@@@@.@.@..@@@@@@..@.@@@@@@@.@@@@@.@@@@@@@@@@@@.@.@@@...@@...@.@.@@@.@@@@.@.@.....@@@@@@..@@@@@@@@..@..@@.@@@@
@.@.@@@@@.@@..@@@@@@.@.@@.@@@@@.@.@@.@@@.@@.@.@....@@@.@@.@@@.@@.@@@@@.@.@@@.@...@@@.@.@@@@@@@.@...@.....@..@@@.@@...@@.@.@@.@.@.@.@.@@@
@@@@.@@@@.@.@.@.@@@@@@@@@@.@@@@@@@@@@@.@.@@.@.@@@...@@@..@@.@..@.@@@@..@..@.@@..@.@@@@@.@@@@@.@.@@...@@@@@@@.@@.@@@@@.@.@@@.@...@...@@.@
@@@.@@@.@@@@..@@...@@.@@@@@@@.@.@.@.@.@.@..@..@@..@@@.@@@@@..@.@@.@@...@.@@..@@@.@@....@@.@@..@@@@.@@.@@@@..@@..@@@@..@@@.@.@@@@.@@@@@.@
@@..@@.@.@@@@.@@@@@@@@.@@@@@.@@@.@.@.@.@.@@@@..@@@@.@@@..@..@..@@@@@@@@@@.@.@.@@@@..@@@@@..@@@@..@..@@@@@@@@...@@.@.@@@@@@@@@@@...@@@.@.
@@.@@@@@.@@@.@@.@.@...@@@.@.....@@@@.@..@@..@..@@@@@.@@..@@@@@@@@@@@.@@.@@.@@..@.@@@@@.@@@@@@@@..@@@....@@@.@@@.@.@....@@.@@.@@..@.@@@..
@@@.@@@.@@.@.@@@@@@@..@@@..@@..@@@..@@@.@.@@.@@@@.@.@@@.@@....@@@.@@.@.@@.@..@....@.@@@@@@@@@.@...@@.@@.@@@@@.@....@@.@..@.@.@@@@@.@.@@.
.@..@@@@.@@@@.@@@@.@.@..@.@....@@@.@@@.@@.@.@..@@@.@@.@.@@.@@@@..@@@@@@@@@.@@@@@@@..@.@@@@@@..@@@@@.@.@@@@@@.@@@.@@@@@@@@@..@@.@@@@@@..@
.@@@.@@...@@@@@..@@..@@@@@@@@@.@@@.@.@@.@@@.....@@.@.@@@@@...@@.@..@@..@@.@@...@@.@...@...@@.....@@@.@..@@@..@@@@@@..@@.@@..@@@.@@@.@@@@
@@@@@@@@@@@@@@@@..@...@..@@.@@@@@..@.@@@@@.@@@@@..@.@@@@@@@.@@@@@...@@@@@@.@...@@@.@@@.@.@@@@.@.@@.@.@..@@.@@@...@@@@@@.@...@.@@@@.@@@@@
.@.@@@@@@.@..@@@@@@@@.@@..@@@@@@...@..@@@@..@@@@.@@.@@@@.@.@@@@.@@@..@@@@@.@@@@@@@..@.@@@.@@@@.@.@@@.@@@.@@@@.@@....@.@..@.@@...@.@..@.@
.@.@.@@.@@@..@@.@@@@@@@@@@@@@@...@@.@@@@@@@..@..@.@@@@@@.....@@.@@.@.@@.@@@@@..@@@@@.@@@..@@.@@.@@@.@.@@@@..@@@.@@@.@@@@@@@.@@.@.@@@@.@.
@.@@@..@@.@.@.@.@@.@..@.@@@.@.@@.@@@@@@@@@.@@@@@@@..@@..@@.@@..@.@@@.@.@@.@.@@@..@..@@@@.@...@..@@@.@@@@.@@@@@.@@.@.@@@@.@@@@@@@..@@@@..
@@@.@@@.@@.@@@@@@@......@.....@.@..@..@@@..@.@@@@..@@.@...@.@@.@@@..@@@@@.@@.@@@.@@@..@.@@..@.@@@@@.@@@@@.@@@.@@@@....@@@@@@.@@.@@@....@
..@@@@@.@@@@.@@..@@@@@@.@.@@.@@@@.......@..@..@.@@@.@@@@@@@.@@@.@@@.@.@..@@@@@.@@@@@.@@.@..@@@@@...@.@..@@@@@.@@@@.@...@@@@@@.@.@@.@@@@@
..@@@@.@.@@@@....@.@@@..@@....@@.@@@.@@@@@.@@@@@@@.@@.@@..@@..@..@@..@@@.@@@@.@.@.@.@@@@.@@.@.@@@..@.@..@@@@@...@.@@..@@@@@..@@@@@..@..@
.@@.@@.@@@@@..@@@@@@@@.@@@@@@@@@.@@.@.@..@@@@..@@..@@.@@...@.@@@@@@@.@@@.@@@..@.@@@.@@@.@@@@@@@.@@.@.@@.@.@@@.@.@.@@@.@@.@...@@@@...@@@@
@@.@@@.@.@@@@@@@...@.@..@@@.@@@@.@.@.@@@@...@@@@@.....@@...@@@@@..@.@@..@@@.@@@.@....@@...@@@.@.@@@@@@@..@@@.@.@@@.@.@..@.@.@@@@....@@..
.@@@@.@@..@.@.@@@@.@@.@@.@@@.@@@.@@..@@@@.@@.@...@@@@@@@@.@@@@....@@@@...@@...@@@...@.@.@@.@..@@@@.@@@.@@@.@@@.@@@@@@@@@@.@@..@.@@@.@@@.
@.@.@@@.@.@.@@@@@@@@..@@@.@.@@@.@@@.@@.@@@..@@@@..@.@..@@@@@.@....@@@@@.@@@@@@.@@@@@.@.@@@@@@@.@@...@.@@@@@@@@.@@@@@.@@..@.@...@.@..@.@@
@..@..@@@@.@@@@@@@.@@@@@@.@@.@@..@.@@@.@@@@@.@@@@@@@.@@@.@@@.@@.@..@@@@@.@...@.@..@.@@.@...@@@.@@.@@.@@@@@@.@@@@@@@@@..@@.@.@@.@@.@..@@@
@.@.@@....@@@.@@@.@.@@...@.@.....@@@@.@.@@.@..@@@.@@@.@@@...@..@@@@.@@@@.@@@@..@@@..@@@@..@@.@@@@.@@@@@@@@@.@@...@..@.@..@@.@@...@@@.@@.
.@@@.@.@@@@@@@..@.@@..@.@..@@@@..@@.@@@.@@.@.@...@.@@@@@..@@.@@.@@@@@..@@...@@@@@@.@@@@@.@....@.@..@@@.@@.@..@.@@@@.@.@@@..@@@@.@@....@@
@@@@@.@.@@@@@@@@@@..@@@@.@@.@@.@.@@@@@@@@@@@@..@@@@@..@@.@..@@@@@.@@...@@@@@@@@@@@@@.@@@@.@@.@@@@@.@@..@@...@@@@.@@@@@@@@@.@.@@@.@@...@@
.@..@@@.@.@@@@.@@@..@@.@....@@@@.@..@.@@..@@@@@@@@.@@..@..@@@@@@@@.@@.@@@.@.@@.@.@.@...@.@.@@.@..@.@@.@.@@@@@@....@@.@@.@@@@@.@@@@@.@@@@
...@.@@@@..@@...@..@@.@@@@@@@@..@@..@@@.@@...@@.@.@.@@@@.@@@.@...@.@@.@@@..@@@@@@@@.@@@@@@..@.@@..@@..@@...@@@......@.@@@.@@.@@@@@@..@@.
@@@@@..@.@.@.@@.@@@.@.@@.@@@@@.@@@@@@@@@@@...@@@@.@@@@@.@@@@@@@..@@@@.@@.@.@..@@..@@..@@@.@@.@@@.@.@@@.@@.@.@@@@.@@@.@@.@@@.@.@..@.@.@@@
.@@@@.@@...@@@@@@@@@..@@@.@..@.@@@@@@@@@.@@.@.@@@.@@.@.@.@@@@@@@.@@@@@@@@@@@....@@@@.@.@.@@@@..@@@@@@.@..@.@@@@.@@@@@@.@@@....@.@@.@...@
@@@@.@...@@@@.@..@.@@.@@.@@@@@@.@@.@@.@@@@@@@@@@@..@..@@.@.@.@@@@.@@@@..@.@@.@@@@...@@@@..@...@.@@@@@@..@.@@.@...@@..@@@@.@.@@@@@@@@@.@.
.@.@@@..@@@..@@.@.@@@@@@@@@.@@.@@@@@@.@@...@.@@@@@@@@@@.@@@@.@.@@..@@@@@.@@.@@@..@@@@@@@@.@@..@..@@@@@@..@.@@.@..@.@.@.@..@@@..@.@@@@.@@
@@......@@@.@@@.@@@.@.@@@@@@.@.@@@@@@@.@@@@@.@.@@@@@.@@.@@@@@.@.@.@@@@@@@@.@@@@@@@.@......@@@.@@@@.@.@@@@@@@.@@@@.@@.@@@.@@.@@@@@@@@@@@@
@@.@@..@....@@.@.@@@@@@@@@@@@..@@.@..@.@@.@@.@.@@.@.@@@.@@..@..@.@@@..@@@.@.@@@..@...@@@@...@@@@@@....@.....@@@@@.@.@@@@.@@@@@.@@@@..@.@
...@..@.@@@.@.@@@...@.@@@@.@.@@.@@.......@@@..@@@@.@.@@@@..@.@@@.@@@@@@@.@.@@@.@@@@.@@@@@@.@..@@@..@..@..@..@@@@@.@@@...@...@@@.@.@.@..@
@@@..@@@.@.@@@..@@...@@.@.@.@@@@@@@.@@@@@..@@@@@@@.@@.@@@.@@@@@@.@.@@@@..@.@..@@@@@@@@@..@.@.@..@@@@@.@@@@@@.@@@@@..@.@@..@.@@@@@@@@@@.@
...@@..@.@@@@@@@.@...@@.@@@@@@@@@@.@.@.@@@@.@@@@@@@.@..@.@@@@...@@@@@.@@@@...@@@@@@@.@...@@@@..@@..@@@..@@.@@@@...@@.@@@@...@@@.@@.@@@@.
.@@.@.@.....@@@@@@@@...@@.@@@...@@@@@.@@@@.@@@..@@@.@.@@@@.@.@@@@@...@@.@@@.@.@@@@..@@@@@@.@.@.@@@.@@@..@..@.@.@@@.@.@..@@@.....@..@..@.
..@.@@@@.@...@.@@@.@@...@.@@@.@..@....@@@@@@..@@@@@.@@.@@@@...@@@..@@@...@.@@@..@@@@@..@@.@@..@...@@..@@@@.@@.@@@.@.@@@@.@@@@@..@@@@@@@.
@..@.@@....@..@@@.@@.@@@..@@@.@@@@@.@@@@..@@.@.@@.@@@@@@@@@.@@@..@@@@@.@@@.@.@@@.@....@@@@@@@@@...@@@@@@@@@@@@.@@@.@@.@@@@....@@@.@@....
@@.@@..@@..@@..@.@@@@@...@...@@..@@@@@.@@.@@@@....@@@.@@@..@@.@@@@@@.@@..@..@.@@.@@@@@..@.@@@.@@.@@.@@.@@.@@@@@@@..@@@@@@.@@.@@@@@..@.@.
.@@.@@....@@..@..@@@.@@.@.@.@..@@@@.@@@.@@@@.@@@..@@@...@..@..@..@@@@@@..@@.@@@@@@@@@@.@@@@..@@.@@@..@.@@@@....@@@@@@.@..@.@@.....@.@@@@
@@@.@@...@@..@@@@.@@@@@@@..@...@@@@.@@@.@.@@@.@@@@@@@@..@.@@.@@@..@..@@@@..@@.@@@@@.@@.@@.@@@@@@@@@@..@.@.@.@@@.@.@@..@.@.@@@@@.@@.@@.@@
@@@.@.@@@@@@@.@@@@.@@@@@@@@.@@@@@.@@@@.@@@.@.@@@.@@@@@@@@@@.@@.@...@@@@..@@@@.@..@@@@@..@@.@@@.@@...@@..@.@.@@@@@@@..@@.@@.@..@..@@@@.@@
.@@.@@.@@@.@.@@@@@.@@.@@@.@.....@@@@@@....@@@@@.@@.@.@@@@@.@@..@..@..@......@.@@@.@@@@..@@..@@@.@...@@.@@@.@@@@@@@.@.@@@.@@@.@@@@@.@@@@.
@@@@..@..@@@.@@.@.@@@@....@...@@.@@.@..@.@@.@@@..@.@.@@@..@.@..@@.......@@@.....@@@@.@.@@@.@.@@..@.@@.@.@..@.@...@.@.@.@@@@@@@@@@@@@....
@@@@@@.@@@@.@....@@.@@@@@@@@@@.@@.@@@..@...@.@@@.@@...@@..@@@@@.@@.@.@@@@@@@@@@.@...@.@@...@..@.@...@.@@@@@@@@@@@..@@...@@@@..@.@@....@@
@@@.@@.@@@@..@@..@.@@.@.@@.@..@.@@@@@..@.@.@@@.@.@..@@@@@@@@@@@..@.@.@.@@.@@@@@@@...@@@.@@.@..@@.@@@@@@@.@@@@@@@@@@@@@@.@@@@.@@@.@.@@@..
@@@.@@@@@.@@@@@@@@@@@@@@..@@.@@.@@.@.@...@@@@@..@@.@@..@..@.@@@..@..@.@@.@@@.@@@@.@@@..@@.@@@@.@.@.@@.@.@@.@@@@@@.@@@@@.@@..@@@@@@@.@.@@
..@@...@@@@@@@.@.@@.@.@@@@@@@.@.@@@@@@@@.@@.@@@@@@@@@.@@@@..@@@@@....@.@@@.@@@@.@@@@@.@...@.@@@@@@@@@.@.@.@.@@@....@@@@.@@.@...@@@@@.@.@
.@...@..@..@@.@@@@@.@...@.@@@.@@@@@.@@@@...@.@.@@@@.@@..@@@@.@@@@.@.@.@..@@.@@.@@........@@.....@.@@@@.@@...@..@@@@@..@@@.@.@@@.@@@.@@@.
..@@@@@@...@@@@@.@@.@@@..@@@@@@@..@@@@.@@@@..@.@@@@@@.@@@@.@@..@@@@@@@.@@.@.@.@@@@.@...@@.@.@@@@.@@@@.@..@@.@@@.@@@@.@.@.@@@@@..@.@....@
@@.@......@@@@@@@@.@.@@@@@@..@..@@.@.@@....@@.@@@@@..@.@@....@.@@@@@.@..@@@.@@..@@@@@@.@@@@.@.@@@@.@.@.@.@@@@.@@@@@.@@.@@@@..@@@.@@@@..@
.@@@@....@....@@@...@@@.@@@@.@@.@@.@..@.@.@.@.@@@.@@...@.@@.@@.@..@@..@.@.@@....@..@@.@@@@@@.@@@..@@...@@.@@@.@@...@@...@@.@@@@@.@@.@@..
@@.@.@@@@@..@...@@@@.@.@@@.@@@@@@@@@@@.@@.@.@.@@.@@.@@@@.@.@.@.@@@...@@@@@.@@..@@@..@@@@@@@@@.@@@@.....@@@@.@@.@@..@..@..@@.@.@@@@@...@.
@.@.@@@@...@@@@.....@@@.@.@@@..@@..@.@@@@.@@.@@@@.@@..@@.@@@@@@@..@.@..@@@.@..@@@@@.@.@.@..@@.@@@.@@@@@....@@@@@.@@@@..@@.@@@@...@..@@.@
@...@@...@@@@.@@@@@.@..@@@...@.@@@..@@...@.@.@@@@@..@..@.@@..@@.@@.@@@.@@.@@@@@.@@@@@..@@@@@@@.@.@@@@.@@@@..@@.@@@.@@@@@@.@@@@@@.@@@@.@@
.@@.....@.@@.@@..@@@@@.@..@@@..@.@@@@@@...@.@@@...@.@@@@@@..@@....@..@.@@.@@.@@@.@@.@..@.@@.@@.@@@@@@@@@@.@@..@@@@@@...@.@@@.@@.@@.@..@@
.@@.@.@.@@@@@.@@@@@@.@.@@.@@.@@.@@@@.@@@@@@@@.@@@@.@@.@....@.@@@@@@.@@.@.@@@.@@@..@.@@.@@@@.@@@@.@.....@.@.@@.@@.@@....@@.@..@.@@.@@@.@@
@.@@.@@..@@@@.@@@@.@@@@..@@@.@@@@@@.@@@@@.@@@..@@@..@@.@..@@@.@@@..@@@@@.@@..@@@@...@@@@@@@@@.@.@.@..@@@.@.@@.@.@@@..@@@@..@@.@@@@@.@@@@
.@@..@.@@..@..@@@@@.@@.@@@.@.@.@@.@@@.@@@.@.@.@@.@.@.@@@.@.....@@.......@.@@@@@.@@@@@..@@.@@..@@@@@.@@.@.@@@@.@@.@@@@@@@@.@.@@.@.@...@@.
@@@.@.@@.@@@@@@.@@@.@.@@@..@@@@@.@@@@.@@.@@.@@.@.@@@.@@@@.@@@@..@@@@@.@@@..@@@.@@@.@.@.@@@@..@@@@.....@.@.@.@@@.@.@..@@.@@@@@.@@@@@@.@@@
....@@@@..@.@@.@@.@@@.@@@.@@..@@@.....@..@...@@@@@.@....@@..@.@@@@@@@@@..@@@@@@.@@@.@@@@@@@@@.@.@@..@@@@@@@@@@@.@@@...@@..@@@@@@@@..@@@@
..@@@@@@@.@@@@.@....@...@@@@@.@.@@..@.@@@@@.@@@@..@.@@.@.@@@@@@@.@@.@.@@@....@@..@@@@@@@@.@@.@.@@.@@.@@.@@.@@@..@@@@@@@@@@@.@.@...@@@@@@
@@@@@.@.@@@@@..@@@@@@@.@@@@@@.@@...@.@..@@.@@@@.@@@@@@@@@@..@...@@.@@@@@@..@@@..@@@.@@@.@@@@@@@@..@@.@@@@..@@.@.@@@...@@@@..@@.@@..@@@@@
...@@...@@@@@..@.@.@..@@.@@.@@.@@@..@@@@@.....@@@@@@@@@@.@..@.@@@@..@@@.@@.@..@@....@.@@@@@@@@@@@@.@@.@@.@@@@@..@@@@@@@@@@@@@..@.@@@@@@@
..@@@..@@@@@@.@@@@@@@.@@@@@@@.@@@@@@...@.@@.@.@.@..@.@@@..@@@@@@.@@@@@@..@@.@@@....@@.@.@.@.@@@@@@@@@.@@@.@.@@@.@@@@.@....@@...@@@@...@@
.@@.@.@..@@@..@@@@@.@@@@@@@@@.@.@..@@@@@@@@@@.@@@@@@@@.@@..@@.@..@@.@..@@.@@...@@@@.@@..@.@.@@@.@@@..@.@@..@@.@@@@...@@.@@@@@@@@.@.....@
@.@.@@@@@.@.@@@@@@..@@@@@@...@@@@@@@@@..@@@.......@.@@@@@@@.@@@@@@@@@@@@@@@.@.@@@@@@@@@@@..@@..@@@@@@@@.@@..@@@@@.@.@@@@@@@@@@@@@@@@@@@.
@@.@.@@..@@@@.@@@@.@.@@@@...@@@..@@@.@@@@.@..@@...@@.@@.@@.@.@..@.@@@@..@@@@@@@@@@@@.@@@@@@@..@@@@@@@@@@.@.@.@@.@@@@@.@.@..@@@..@@.@@@..
..@@@...@@@@@@.@.@@.@@@@@...@.@@@.@@....@@@@@@@@@@.@@.@@@.@@..@@@@@.@..@@@@@.@@@@@.@.@.@@...@.@@.@.@@.@@@@@.@@@@..@@@@@@..@@..@@@@@@@@@.
@@..@@.@@@@@@@@@@@.@.@@@@@.@..@@@.@@@@@@@@@@..@@@@.@..@@@@@.@.@@@.@.@....@@.@..@..@@@@@@@@@@.@@..@@@..@.@@.@@.@.@@@@@...@@@.@@@.@@@.@@@@
@@.@@.@.@@.@@@@@@@@..@@@@@@@.@@@..@@.@..@@.@..@@@@@@.@@@@@@.@@@..@..@@@@..@@.@@@@@@.@@.@@.@@@.@@.@@@.@...@.@@.@.@@.@@....@@@@@...@@..@.@
@...@@@@..@..@@.@@@.@@@@@@@@@..@.@@...@@@@@@@....@@.@...@@.@@.@@.@@.@@@@@@@.@@@..@.@@@@@.@@..@@@@@@@.@@@.@@.@@@.@@@..@...@@...@@@@@@.@..
@..@..@.@@@@@..@@@@.@@@@@@.@@..@@..@@.@..@@.@@.@@@.@.@.@@..@@...@@.@.@@.@..@@@...@@.@@@.@@@@.@@.@@@...@@@.@@@.@@@.@@@.@@@@@@.@@@..@@@@@@
.@@.@@@@@@@@@@@.@.@@@@@.@.@.@@@@.@@.@@..@@@.@@@@..@@...@@..@@@@@@.@@.@@..@@@@@.@...@.@@@@@@@.@@...@@@.@@...@@@@...@@.@@.@.@..@.@@@.@@@@@
@.@..@@.@@..@@@@@@@@@@@@..@..@@@@@@@@.@...@..@@@..@@@@.@@@@@..@@@@@@.@@@@@@@@@.@@@.@@@.@@......@@@..@@@.@..@.@@.@.@@.@....@..@@@.@@@.@.@
..@@@.@@@@.@@@@.@@@@@@@@@@@@@@@@..@..@@@..@@@..@@@@@.@@.@...@@.@@@@..@@..@@.@.@.@@..@.@@@@@@.@.@.@..@@@.@@.@@.@..@@@@@.@..@@@@@@@@@.@.@@
@.@@.@@@@.@@@@@@@@@@.@.@@@@@@@@@.@.@@@@...@....@@@@@@@@.@@..@@@..@@.@@@@@@@@@@@.@@@@..@@.@.@@..@@@.@@@@@@@..@...@@..@@@@.@@@@@.@.@@...@.
.@.@@@@..@@@@@.@..@@.@@.@@@@..@@..@.@@@..@.@.@@@@@.@..@@@..@.@@@.@@@@..@.@.@@@@@@...@..@@@...@.@..@@@@......@@@@.@@@@@@.@@@..@..@@@@@@.@
.@..@.@.@..@.@@@.@.@@.@.@@.@.@@.@@@@@.@@@@@@@...@@@@@.@.@.@@.@@.@.@@.@@.@..@@.....@@@@@.@.@...@.@.@@@.@@@.@..@@@@.@.@.@@@@@..@@@.@@@.@@@
@@..@@.@.@..@.@@@@.@@@@.@@@@@@..@@@@.@.@@..@@@@..@@.@@@@@@@@@...@@.@@.@.@@@@@@.@@@.@@@@@@@@@.@@.@@@@@@.@@@@@@.@@@@@@@@@@.@@...@.@.@@...@
.@.@@@@@@@.@.@@.@..@.@.@@@@@@@.@.@@@@@@.@@....@@@@.@@.@@..@.@@..@@@@@@@....@@@..@@.@..@@@.@@.@...@@@@..@..@@@@@...@@..@@@.@@@..@@@..@@@.
@..@@@@.@..@@@@@.@@.@@.@@@@.@@@..@@.@@@@@.@@@@@.@@@@@@.@..@@...@@...@.@.@@.@@@....@....@@@@@..@@@@@@.@@@@@.@.@@.@@@.@@.@.@.@@@@@@@@@.@..
@..@@.@.@.@@@.@..@@@.@.@.@@@@..@@....@@@.@@@@.@@...@@.@@@....@..@.@..@.@@...@@.....@...@@@@.@..@.@.@..@@...@@.@....@@@@@@@@@@@@@@...@@.@
@@@..@.@....@@@@.@@@.@@@.@@@@@@@@@@.@@...@@@..@@.@.@@.@..@@@.@@..@.@.@@@@@@...@@..@@@@...@@.@@@@...@.@.@@@@@.@@@@.@@@@..@@..@..@@@.@...@
@@.@@.@@.@..@@@..@@@@..@@@@.@@@.@.@@@@.@@.....@.@@@.@.@..@@.@@@@@@@.@@@.@.@@@@@@@@@@.@@@.@.@@@.@@@@@@.@.@..@@@..@@@.@@.@..@@..@@@@@@@@@@
@@@...@.@...@@.@@@.@@..@@@.@@@@.@@..@@.@.@.@@.@@.@@.@@@@@@@@.@.@@@@.@.@@..@@.@.@@@@@.@..@@@@@@@@......@@@@@@@@@@.@....@..@@@.@.@@@@.@..@
.@@@@@@@@.@@@@@.@.@@@@@@@@@.@@@.@@@.@@@.@.....@@@@@@@.@@@@@@.@@@@@@.@@@@.@.@.@.@@@@.@@@@@@.@@@@..@@@.@@@.@.@@@.@@@@@@@@@@@.@.@.@...@...@
...@@@@@.@.@..@@.@@@@.@@@@@@@.@@@@.@@@..@.@@@@@@@.@.@@..@@..@@.@@@@@@.@@@@.@.@..@@@.@@.@@@@..@.@@@@@@@@@@@.@@.@@@...@@@@@.@@.@.@@@.@@@.@
..@.@@@@@@.@.....@.@@..@...@..@@@@@@.@..@@@.@.@.@@.@.@@@@..@@@..@@@@@@@.@@@.@.@@@@@@..@@...@.@@.@..@@@@@.@..@@@..@@@.@@@@.@.@@...@@@.@@@
@@@.@@@@@@@@@....@@@.@@@@@@...@@@.@@@.@.@@@@@.@@@@...@@.@@@...@@@@@@@@@@@@@@@.@.@@@.@@@@@@@@@@.@@@@@@..@@.@.@@@..@@@.@@@@@@@.@@@@@@@@..@
@.@@@@@.@..@..@@@.@@..@@@@@@@@@.@@@@@@@@.@..@@.@@@.@@.@.@@@@.....@.@@.@.@@@.@.@@@...@@@.@.@.@.@..@.@@@@.@@...@@..@@..@.@@.@@.@@@@.@.@@@@"""

In [20]:
input = """..@@.@@@@.
@@@.@.@.@@
@@@@@.@.@@
@.@@@@..@.
@@.@@@@.@@
.@@@@@@@.@
.@.@.@.@@@
@.@@@.@@@@
.@@@@@@@@.
@.@.@@@.@."""

In [25]:
data = [[0 if c == '.' else 1 for c in list(line)] for line in input.split()]
data

[[0,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  1],
 [1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  0,
  1,
  0,

# Part 1

In [26]:
import numpy as np
from scipy.signal import convolve2d
npdata = np.array(data)

mask = np.array([[1, 1, 1],[1, 0, 1],[1, 1, 1]])
sumsarray = convolve2d(npdata, mask, boundary='fill', fillvalue=0, mode='same')

resultmatrix = np.multiply(npdata, sumsarray)
boolmatrix = np.multiply((resultmatrix < 4), npdata)
np.count_nonzero(boolmatrix)

np.int64(1320)

# Part 2

In [ ]:
npdata = np.array(data)
test = True
mask = np.array([[1, 1, 1],[1, 0, 1],[1, 1, 1]])
sum = 0
while(test):
    test = False
    sumsarray = convolve2d(npdata, mask, boundary='fill', fillvalue=0, mode='same')
    resultmatrix = np.multiply(npdata, sumsarray)
    boolmatrix = np.multiply((resultmatrix < 4), npdata)
    amount_removed = np.count_nonzero(boolmatrix)
    if amount_removed > 0:
        test = True
        sum += amount_removed
        npdata = np.bitwise_xor(npdata, boolmatrix)
sum

---------------------------------
[[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 1]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 1 1 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
---------------------------------
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
---------------------------------
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
---------------------------------
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
---------------------------------
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
---------------------------------
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
---------------------------------
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 

np.int64(8354)